delayed_ensemble:
  dataset: 'cifar10'
  model: 'SimpleCNN'
  n_epochs: 200
  n_ensembles: 3
  batch_size: 128
  learning_rate: 0.1
  delayed_starts: [0, 1, 3, 5, 10, 30, 50, 100, 200]

noisy_labels:
  dataset: 'cifar10'
  model: 'SimpleCNN'
  n_epochs: 200
  n_ensembles: 3
  batch_size: 128
  learning_rate: 0.1
  num_rand_labels: [0, 10000, 20000]
  severity: 5

regularizers:
  dataset: 'cifar10'
  n_epochs: 200
  n_ensembles: 4
  batch_size: 128
  learning_rate: 0.1
  dropouts: [0, 0.5]
  mixup_alphas: [0, 1.0, 2.0, 8.0]
